# This is a basic workflow to help you get started with Actions

name: Netlify Deployment

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Netlify uses Ubuntu 16.04 backend OS
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
