name: Build

on:
  # Trigger workflow on master branch push or pull request events
  push:
    branches: [ master, dev]
  pull_request:
    branches: [ master ]

  # Run workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Netlify uses Ubuntu 16.04 backend OS
        # Also build for latest ubuntu to check support
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        # Netlify uses v12
        # Also build other version to check support
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      # Setup Node JS
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Install Node JS package dependences
      # 'package-lock.json' is removed to solve issue with different package-lock versions
      - name: Install packages
        run: |
          rm package-lock.json
          npm i
      # Run tests
      - name: Test
        run: npm test
      # Build production app
      - name: Build
        run: |
          npm run build --if-present