name: Build

on:
  # Trigger workflow on master branch push or pull request events
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Run workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Netlify uses Ubuntu 16.04 backend OS
        # Also build for latest ubuntu to check support
        os: [ubuntu-16.04, ubuntu-latest]
        # Netlify uses v12
        # Also build other version to check support
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm ci
          npm run build --if-present
      - name: Test
        run: npm test